export default {
  SET_PLAY_STATE: "SET_PLAY_STATE",
  SET_PLAY_URL: "SET_PLAY_URL",
  SET_PLAY_INDEX: "SET_PLAY_INDEX",
  SET_PLAY_ID: "SET_PLAY_ID",
  SET_PLAY_LIST: "SET_PLAY_LIST",
  SET_PLAY_SEQUENCE: "SET_PLAY_SEQUENCE",
  SET_PLAY_VOLUME: "SET_PLAY_VOLUME",
  SET_PLAYER_SHOW: "SET_PLAYER_SHOW",


  SET_PLAY_DRAG: "SET_PLAY_DRAG",
  SET_PLAY_LIST_TOAST: "SET_PLAY_LIST_TOAST",



  SET_CURRENTSONG: "SET_CURRENTSONG",
  SET_CURRENTTIME: "SET_CURRENTTIME",
  SET_DURATION: "SET_DURATION",



  SET_MV_ID: "SET_MV_ID",
  SET_MV_SHOW: "SET_MV_SHOW",






  SET_MUSIC: "SET_MUSIC",
  SET_MV: "SET_MV",
  SET_LOGIN: "SET_LOGIN",
}