export default {
  SET_PLAY_STATE: "SET_PLAY_STATE",
  SET_PLAY_URL: "SET_PLAY_URL",
  SET_PLAY_INDEX: "SET_PLAY_INDEX",
  SET_PLAY_ID: "SET_PLAY_ID",
  SET_PLAY_LIST: "SET_PLAY_LIST",
  SET_PLAY_LIST_SHOW: "SET_PLAY_LIST_SHOW",
  SET_PLAY_SEQUENCE: "SET_PLAY_SEQUENCE",
  SET_PLAY_DRAG: "SET_PLAY_DRAG",

  SET_CURRENTSONG: "SET_CURRENTSONG",
  SET_CURRENTTIME: "SET_CURRENTTIME",
  SET_DURATION: "SET_DURATION",
}