export default {
  SET_PLAY_STATE: "SET_PLAY_STATE",
  SET_PLAY_URL: "SET_PLAY_URL",
  SET_PLAY_INDEX: "SET_PLAY_INDEX",
  SET_PLAY_LIST: "SET_PLAY_LIST",
  SET_PLAY_SEQUENCE: "SET_PLAY_SEQUENCE",
  
  SET_CURRENTSONG: "SET_CURRENTSONG",
  SET_CURRENTTIME: "SET_CURRENTTIME",
  SET_DURATION: "SET_DURATION",
}